name: ForcePlugin
version: 3.0
main: org.perseus.forcePlugin.ForcePlugin
api-version: 1.21
author: Perseus

commands:
  force:
    description: Choose your side in the Force.
    usage: /<command> choose <light|dark>
  forcestats:
    description: Displays your Force progression stats.
    usage: /<command> [player]
    aliases: [fs]
  forceadmin:
    description: Admin command for the ForcePlugin.
    usage: /<command> [sub-command]
    aliases: [fa]

permissions:
  forceplugin.admin:
    description: Grants access to all /forceadmin commands and checking other players' stats.
    default: op
  forceplugin.use:
    description: Grants access to the basic player commands.
    default: true