name: ForcePlugin
version: 1.0
main: org.perseus.forcePlugin.ForcePlugin
api-version: 1.21
author: Perseus

commands:
  force:
    description: Choose your side in the Force.
    usage: /<command> choose <light|dark>
  powers:
    description: Toggles your Force abilities on or off.
    usage: /<command> <on|off>
  abilities:
    description: Opens the ability selection menu.
    usage: /<command>
  # --- NEW ---
  forceadmin:
    description: Admin command for the ForcePlugin.
    usage: /<command> [reload|setside|reset|check]
    aliases: [fa] # Allows players to use /fa as a shortcut

# --- NEW: Permissions ---
permissions:
  forceplugin.admin:
    description: Grants access to all /forceadmin commands.
    default: op # Only server operators will have this by default.
  forceplugin.use:
    description: Grants access to the basic player commands (/force, /powers, /abilities).
    default: true # All players will have this by default.