name: ForcePlugin
version: 1.0
main: org.perseus.forcePlugin.ForcePlugin
api-version: 1.21
author: Perseus

commands:
  force:
    description: Choose your side in the Force.
    usage: /<command> choose <light|dark>
  powers:
    description: Toggles your Force abilities on or off.
    usage: /<command> <on|off>
  abilities:
    description: Opens the ability selection menu.
    usage: /<command>
  forceadmin:
    description: Admin command for the ForcePlugin.
    usage: /<command> [reload|setside|reset|check|setlevel|givexp|givepoints]
    aliases: [fa]
  forcestats:
    description: Displays your Force progression stats.
    usage: /<command> [player]
    aliases: [fs]

permissions:
  forceplugin.admin:
    description: Grants access to all /forceadmin commands and checking other players' stats.
    default: op
  forceplugin.use:
    description: Grants access to the basic player commands.
    default: true